# Jekyll configuration for Postsvg documentation
# Uses Just the Docs theme - https://just-the-docs.com/

# Site settings
title: Postsvg Documentation
description: Pure Ruby PostScript to SVG converter with comprehensive validation and optimization
url: https://metanorma.github.io
baseurl: /postsvg

# Theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# AsciiDoc support
asciidoc: {}
asciidoctor:
  attributes:
    - idprefix=_
    - source-highlighter=rouge
    - icons=font
    - experimental=''
    - sectanchors=''
    - toc=left

# Build settings
plugins:
  - jekyll-asciidoc
  - jekyll-seo-tag

# Just the Docs theme configuration
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# Navigation
nav_sort: case_insensitive
nav_fold: true

# Footer content
footer_content: 'Copyright &copy; Ribose. Licensed under the <a href="https://opensource.org/licenses/BSD-2-Clause">BSD 2-Clause License</a>.'

# Color scheme - use light mode
color_scheme: light

# Logo
logo: false

# Aux links for the upper right navigation
aux_links:
  "Postsvg on GitHub":
    - "https://github.com/metanorma/postsvg"
  "Report Issue":
    - "https://github.com/metanorma/postsvg/issues"
  "RubyGems":
    - "https://rubygems.org/gems/postsvg"

# Aux links configuration
aux_links_new_tab: true

# Heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      nav_exclude: false

# Only process AsciiDoc files
include:
  - "*.adoc"

# Exclude everything else
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Set permalink structure
permalink: pretty

# Note: When running from docs/ directory, do not set source
# When running from project root, use: source: docs